declare -A APACHE_NAMES=(
    ["apt-get"]="apache2"
    ["pacman"]="apache"
    ["dnf"]="httpd"
    ["yum"]="httpd"
)

declare -A DB_NAMES=(
    ["apt-get"]="postgresql"
    ["pacman"]="postgresql"
    ["dnf"]="postgresql-server"
    ["yum"]="postgresql-server"
)
